Fixed showed error message when executing Unit Test cases.
Why:
error: SEH exception with code 0xc0000005 thrown in the test.

HowToFix:
Access a member of a NULL object, but the object came from a wrong place. Use input parameter instead of the NULL object.